"""Agregar campo summary a ConversationMemory

Revision ID: 3a132569f97b
Revises: 1920f7e79495
Create Date: 2025-01-15 11:04:26.740395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a132569f97b'
down_revision = '1920f7e79495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_memory', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
